### ISSUE TITLE
Issue on TestHarness 

### ISSUE THREAD

**Issue by interman** [daishisystems/Daishi.PaySharp#4]
Hi

I try to follow your tutorial to run test harness example.

I get the problem on

Open your web browser and navigate to https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-XXXXXXXX ( the token return from step 5)

the browser jump to error page with error:
We cannot process this transaction because there is a problem with the PayPal email address supplied by the seller. Please contact the seller to resolve the problem. If this payment is for an eBay listing, you can contact the seller via the "Ask Seller a Question" link on the listing page. When you have the correct email address, payment can be made at www.paypal.com.

The purchase couldn't be completed
There's a problem with the merchant's PayPal account. Please try again later.

I guess may be my setting is incorrect and I want to clarify:

Are all User. Password and Signature from my sandbox test account => profile=>  API Credentials?

Or I should find out this information from my main account somewhere?

Can you explain more detail how and where to find all informations.

Thanks

**Comment by interman** [comment]
I resolved the problem by NOT set subject.   I just wonder is it optional parameter?  Can I simple put empty string on the field?

**Comment by daishisystems** [comment]
This seems to be a rare issue. Please check out [this thread](https://www.prestashop.com/forums/topic/266127-paypal-error/) to resolve. Here is the synopsis:

> Under your PayPal API settings, make sure your PayPal Business Account is the confirmed (verified) email address that you have in PayPal. I was passing the verification check within the module, but receiving the same error message, until I changed the business name to match my email address.

**Comment by interman** [comment]
I found the solution from [here](https://developer.paypal.com/docs/classic/api/PayPalSOAPAPIArchitecture/) ,  it mentions subject can be either Authorizing-Merchant-Email -or- Authorizing-Merchant-Account-ID.  Because sandbox test accounts has no merchant-account-id, so I use merchant-email, which is sandbox test account Email ID.

If you don't mind, can you update the front page sample with this information to help other developer know to place the Email ID in subject field?

Thanks
